
export const ADD_EXPENSE = "ADD_EXPENSE";
export const REMOVE_EXPENSE = "REMOVE_EXPENSE";
export const SHOW_EXPENSE_MODAL = "SHOW_EXPENSE_MODAL";
export const HIDE_EXPENSE_MODAL = "HIDE_EXPENSE_MODAL";